#!/usr/bin/env python3
from control_utils import utils
import rospy

if __name__ == '__main__':
    # Initializing the node
    rospy.init_node("controller_node", anonymous=True)
    controller = utils.Controller()

    # if current x position is greater than 1.1, goes back and
    # if current x position is less than 0.9, goes front
    while True:
        position = controller.get_position()
        if position is None:
            continue

        if position[0] > 1.1:
            controller.go_back()
        elif position[0] < 0.9:
            controller.go_front()
        else:
            break

    rospy.spin()
